<?php

/**
 * @file Memberform module.
 */

/**
 * Include form page definitions.
 */
module_load_include('inc', 'memberform', 'memberform_helpers');

// Include form definition files in /pages.
module_load_include('inc', 'memberform', 'multipage_forms/includes/memberform_pages_helpers');
module_load_include('inc', 'memberform', 'multipage_forms/includes/memberform_shared_forms');
$form_names = memberform_get_formnames();
foreach ($form_names as $form_name) {
  module_load_include('inc', 'memberform', 'multipage_forms/memberform_' . $form_name . '_pages');
}

/**
 * Implements hook_menu().
 */
function memberform_menu() {
  $items = array();
  $form_names = memberform_get_formnames();
  foreach ($form_names as $form_name) {
    $settings_callback = 'memberform_' . $form_name . '_settings';
    $path_name = $settings_callback('path_name');
    $form_title = $settings_callback('form_title');
    $items[$path_name] = array(
      'title' => $form_title,
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'memberform_get_form',
      'page arguments' => array('memberform_form', $form_name),
      'file' => 'memberform_form.inc',
      'access callback' => TRUE,
    );
  }

  $items['admin/config/sp/aanmelden'] = [
    'title'            => 'Aanmeldformulieren',
    'description'      => 'Aanmeldingen bekijken en de formulieren instellen.',
    'type'             => MENU_NORMAL_ITEM,
    'page callback'    => 'memberform_view_submissions',
    'access callback'  => 'user_access',
    'access arguments' => ['administer signup forms'],
    'file'             => 'memberform_page_admin.inc',
  ];

  $items['admin/config/sp/aanmelden/submissions'] = [
    'title'            => 'Inschrijvingen',
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'access callback'  => 'user_access',
    'access arguments' => ['access pending submissions'],
    'weight'           => -2,
  ];

  $items['admin/config/sp/aanmelden/submission/%'] = [
    'title'            => 'Inschrijving bekijken',
    'type'             => MENU_CALLBACK,
    'page callback'    => 'memberform_submission_details',
    'page arguments'   => [5],
    'access callback'  => 'user_access',
    'access arguments' => ['access pending submissions'],
    'file'             => 'memberform_page_admin.inc',
    'weight'           => -1,
  ];

  $items['admin/config/sp/aanmelden/gifts'] = [
    'title'            => 'Welkomstgeschenken',
    'type'             => MENU_LOCAL_TASK,
    'page callback'    => 'memberform_gifts_view',
    'access callback'  => 'user_access',
    'access arguments' => ['administer signup forms'],
    'file'             => 'memberform_page_admin.inc',
    'weight'           => 1,
  ];

  $items['admin/config/sp/aanmelden/gifts/edit'] = [
    'title'            => 'Geschenk toevoegen',
    'type'             => MENU_CALLBACK,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => ['memberform_gifts_form'],
    'access callback'  => 'user_access',
    'access arguments' => ['administer signup forms'],
    'file'             => 'memberform_page_admin.inc',
    'weight'           => 2,
  ];

  $items['admin/config/sp/aanmelden/gifts/edit/%'] = [
    'title'            => 'Geschenk bewerken',
    'type'             => MENU_CALLBACK,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => ['memberform_gifts_form', 6],
    'access callback'  => 'user_access',
    'access arguments' => ['administer signup forms'],
    'file'             => 'memberform_page_admin.inc',
    'weight'           => 3,
  ];

  $items['admin/config/sp/aanmelden/settings'] = [
    'title'            => 'Instellingen',
    'description'      => 'Instellingen voor de aanmeldformulieren',
    'type'             => MENU_LOCAL_TASK,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => ['memberform_admin_settings_form'],
    'access callback'  => 'user_access',
    'access arguments' => ['administer signup forms'],
    'file'             => 'memberform_page_admin.inc',
    'weight'           => 12,
  ];

  $items['admin/config/sp/aanmelden/submit'] = [
    'title'            => 'Wachtende inschrijvingen verwerken',
    'type'             => MENU_CALLBACK,
    'page callback'    => 'memberform_admin_submit_pending',
    'access callback'  => 'user_access',
    'access arguments' => ['access pending submissions'],
    'file'             => 'memberform_page_admin.inc',
    'weight'           => 13,
  ];

  $items['aanmelden/bedankt'] = [
      'title'           => 'Bedankt voor je aanmelding',
      'type'            => MENU_CALLBACK,
      'page callback'   => 'memberform_page_thanks',
      'access callback' => TRUE,
      'file'            => 'memberform_page_actions.inc',
  ];

  $items['aanmelden/fout'] = [
      'title'           => 'Er is een fout opgetreden',
      'type'            => MENU_CALLBACK,
      'page callback'   => 'memberform_page_error',
      'access callback' => TRUE,
      'file'            => 'memberform_page_actions.inc',
  ];

  $items['aanmelden/bevestig/%'] = [
    'title'           => 'Aanmelding bevestigen',
    'type'            => MENU_CALLBACK,
    'page callback'   => 'memberform_page_validate',
    'page arguments'  => [2],
    'access callback' => TRUE,
    'file'            => 'memberform_page_actions.inc',
  ];

  return $items;
}

/**
 * Implements hook permission.
 */
function memberform_permission() {
  return
    [
      'administer signup forms' =>
        [
          'title'       => t('Aanmeldformulieren beheren'),
          'description' => t('Beheer instellingen en welkomstgeschenken voor de aanmeldformulieren.'),
        ],
    'access pending submissions' =>
    [
      'title'       => t('Wachtende aanmeldingen bekijken'),
      'description' => t('Bekijk en synchroniseer wachtende aanmeldingen.'),
    ],
    'access internal signup form' =>
    [
      'title'       => t('Intern aanmeldformulier'),
      'description' => t('Toegang tot intern aanmeldformulier.'),
    ],
  ];
}

/**
 * Custom form callback to pass arguments.
 *
 * @param string $form_callback
 *   General form callback for all forms and pages.
 * @param string $form_name
 *   Name of the form to display.
 *
 * @return array
 *   Drupal form render array.
 */
function memberform_get_form($form_callback, $form_name) {
  return drupal_get_form($form_callback, $form_name);
}

/**
 * Implements hook_cron().
 */
function memberform_cron() {

  $lastrun = variable_get('memberform_cron_lastrun');
  if ($lastrun < (time() - 3600)) {
    variable_set('memberform_cron_lastrun', time());
    memberform_submit_pending();
    memberform_send_reminders();
  }
}

/**
 * Implements hook_mail().
 */
function memberform_mail($key, &$message, $params) {
  switch ($key) {
    case 'verificatie':
      memberform_get_mail($message, $params);
      break;

    case 'reminder':
      memberform_get_reminder_mail($message, $params);
      break;
  }
}
